seed:
  2333
data:
  edh_dir: "data/test/edh"
  era5_dir: "data/test/era5"
  val_ratio: 0.2
  num_workers: 1
  persistent_workers: True
  seq_len: 32
model:
  input_length: 16
  total_length: 32
  img_width: 64
  img_height: 64
  img_channel: 7
  out_channel: 1
  num_hidden: [64,64,64,64]
  patch_size: 4
  filter_size: 5
  stride: 1
  layer_norm: 1
optim:
  # reverse_scheduled_sample
  reverse_scheduled_sampling: 1
  sampling_start_value: 1.0
  r_sampling_step_1: 5000
  r_sampling_step_2: 10000
  r_exp_alpha: 1000
  # gpu
  device: "cuda:0"
  accelerator: "gpu"
  precision: "32"
  batch_size: 32
  float32_matmul_precision: "medium"
  # optimizer
  method: "adam"
  lr: 1e-4
  betas: [0.5, 0.9]
  gradient_clip_val: 1.0
  max_epochs: 100
  accumulate: 1
  weight_decay: 1e-4
  # scheduler
  warmup_percentage: 0.1
  lr_scheduler_mode: "cosine"
  min_lr_ratio: 1e-3
  warmup_min_lr_ratio: 0.1
  # early stopping
  monitor: "val/loss"
  patience: 15
